### ISSUE TITLE
Cannot scroll to the end of a conversation

### ISSUE THREAD

**Issue by bbenoist** [Odonno/Modern-Gitter#53]
On my Win 10 mobile device (both the phone screen and continuum) it is impossible to scroll to the end of a conversation. Whenever I try to go down, the app scrolls up 1 second after.

Apart from text, the conversation contains an image and multiple quotes.

**Comment by gep13** [comment]
@bbenoist the development of the UWP version of the Modern Gitter application has moved to here:

https://github.com/Odonno/modern-gitter-winjs

And this issue is being tracked here:

https://github.com/Odonno/modern-gitter-winjs/issues/20

Would be interesting to know how you ended up in this repo, rather than the other one.  Perhaps a link needs to be changed somewhere?

**Comment by bbenoist** [comment]
> @bbenoist the development of the UWP version of the Modern Gitter application has moved to here:

> https://github.com/Odonno/modern-gitter-winjs

> And this issue is being tracked here:

> Odonno/modern-gitter-winjs#20

OK thank you for the info

> Would be interesting to know how you ended up in this repo, rather than the other one. Perhaps a link needs to be changed somewhere?

[Looks like this repository is better ranked than the UWP one](http://lmgtfy.com/?q=modern+gitter+github&l=1) :wink:

**Comment by Odonno** [comment]
@bbenoist Thank you for your feedback ! Indeed, this repository is not the previous host for the WP8.1, so not for the W10 version.

I will soon set this one as deprecated, link everyone to the new repository and remove issues feature so no one could make a mistake.
